language: node_js
node_js:
- 10

stages:
  - build
  - test
  - name: deploy
    if: branch =~ /^feature\/.*$/

install:
- npm i

jobs:
  include:
    # BUILD
    - stage: build
      script: npm run build

    # TEST
    - stage: test
      script: npm run test

    # DEPLOY
    - stage: deploy
      script: 
        - npm i firebase-tools
        - firebase deploy --only functions --token=${FIREBASE_TOKEN}     