language: node_js
node_js:
  - 10

stages:
  - install
  - build
  - test
  - name: deploy
    if: branch =~ /^feature\/.*$/

jobs:
  include:
    # INSTALL
    - stage: install
      script: npm i
      workspaces:
        # Upload node_modules
        create:
          name: node_modules
          paths:
            - node_modules

    # BUILD
    - stage: build
      workspaces:
        # Donwload node_modules
        use:
          - node_modules
        # Upload dist folder
        create:
          name: dist
          paths:
            - dist
      script: npm run build

    # TEST
    - stage: test
      workspaces:
        # Donwload node_modules
        use:
          - node_modules
      script: npm run test

    # DEPLOY
    - stage: deploy
      workspaces:
        # Donwload dependencies
        use:
          - node_modules
          - dist
      script: 
        - npm i firebase-tools
        - firebase deploy --only functions --token=${FIREBASE_TOKEN}     