language: node_js
node_js:
  - 8

stages:
  - build
  - test
  - name: deploy
    if: branch =~ /^feature\/.*$/

# Skip npm install before each stage
install: true

jobs:
  include:
    # BUILD
    - stage: build
      script:
        - npm i 
        - npm run build
      workspaces:
        # Upload node_modules and dist folder
        create:
          name: dependencies
          paths: 
            - node_modules
            - dist

    # TEST
    - stage: test
      workspaces:
        # Donwload dependencies
        use: dependencies
      script: npm run test

    # DEPLOY
    - stage: deploy
      workspaces:
        # Donwload dependencies
        use: dependencies
      script: 
        - npm i firebase-tools
        - firebase deploy --only functions --token=${FIREBASE_TOKEN}     